kubectl apply -f  ./k8s/mq-poc-secret.yaml
kubectl apply -f  ./k8s/mq-poc-configmap.yaml
kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/download/v1.14.0/cluster-operator.yml
kubectl apply -f  ./k8s/rabbitmq-cluster-operator.yaml
kubectl apply -f  ./k8s/mq-poc-publisher.yaml
kubectl apply -f  ./k8s/mq-poc-worker.yaml
kubectl apply -f  ./k8s/mq-poc-ingress.yaml
kubectl apply -f  ./k8s/silo-dashboard/silo-dashboard-db.yaml
kubectl apply -f  ./k8s/silo-dashboard/silo-dashboard.yaml