apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeworker
  labels:
    app: nodeworker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeworker
  template:
    metadata:
      labels:
        app: nodeworker
    spec:
      imagePullSecrets:
        - name: app-docker-dev
      initContainers:
        - name: wait-for-rabbitmq
          image: travelping/nettools
          args:
          - /bin/bash
          - -c
          - 'until nc -zv rabbitmq-server 5672; do sleep 5;done;'
      containers:
      - name: nodeworker
        image: dog830228/mq_poc-nodeworker
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 300Mi
        env:
          - name: DBConnection
            value: "Data Source=sqlserver;Initial Catalog=orleans;User ID=sa;Password=test.123;"
        envFrom:
          - configMapRef:
              name: npq-poc-env
          - secretRef:
              name: mq-poc-secret
              optional: true



