apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-server
spec:
  image: rabbitmq:3.9.4-management
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest